#!/bin/bash

echo "🔧 CONFIGURACIÓN DE APIS DE TRANSCRIPCIÓN"
echo "=========================================="
echo ""
echo "Para que el sistema pueda transcribir videos y audios automáticamente,"
echo "necesitas configurar al menos una API de transcripción."
echo ""
echo "📋 OPCIONES DISPONIBLES:"
echo ""
echo "1. 🚀 OPENAI API (Recomendado - Más fácil)"
echo "   • Ve a: https://platform.openai.com/api-keys"
echo "   • Crea una cuenta gratuita"
echo "   • Genera una API key"
echo "   • Costo: ~$0.006 por minuto de audio"
echo ""
echo "2. 🆓 ASSEMBLYAI (Gratuito hasta 3 horas/mes)"
echo "   • Ve a: https://www.assemblyai.com/"
echo "   • Crea una cuenta gratuita"
echo "   • Obtén tu API key"
echo "   • Gratuito: 3 horas de transcripción por mes"
echo ""
echo "3. ☁️ AZURE SPEECH SERVICES"
echo "   • Ve a: https://portal.azure.com/"
echo "   • Crea un recurso de Speech Services"
echo "   • Obtén la key y región"
echo ""
echo "4. 🌐 AWS TRANSCRIBE"
echo "   • Ve a: https://aws.amazon.com/transcribe/"
echo "   • Configura credenciales AWS"
echo "   • Requiere bucket S3"
echo ""
echo "5. 🔍 GOOGLE CLOUD SPEECH-TO-TEXT"
echo "   • Ve a: https://cloud.google.com/speech-to-text"
echo "   • Configura proyecto y credenciales"
echo ""

echo "📝 INSTRUCCIONES DE CONFIGURACIÓN:"
echo "=================================="
echo ""
echo "1. Elige una de las opciones anteriores"
echo "2. Obtén tu API key"
echo "3. Crea un archivo .env en la carpeta backend con:"
echo ""
echo "   # Para OpenAI:"
echo "   OPENAI_API_KEY=tu_api_key_aqui"
echo ""
echo "   # Para AssemblyAI:"
echo "   ASSEMBLY_AI_KEY=tu_api_key_aqui"
echo ""
echo "   # Para Azure:"
echo "   AZURE_SPEECH_KEY=tu_api_key_aqui"
echo "   AZURE_SPEECH_REGION=tu_region_aqui"
echo ""
echo "4. Reinicia el servidor Rails"
echo ""

echo "🔄 ALTERNATIVA TEMPORAL:"
echo "========================"
echo ""
echo "Si no quieres configurar una API ahora, puedes:"
echo ""
echo "1. 📝 Transcribir manualmente tu video/audio"
echo "2. 📄 Guardar la transcripción como archivo .txt"
echo "3. 📤 Subir el archivo .txt en lugar del video"
echo ""
echo "El sistema procesará el archivo de texto normalmente."
echo ""

echo "❓ ¿Necesitas ayuda con alguna configuración específica?"
echo "   Puedes consultar la documentación en:"
echo "   - backend/TRANSCRIPTION_SETUP.md"
echo "   - backend/README.md"
echo ""

read -p "¿Quieres que te ayude a configurar alguna API específica? (s/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Ss]$ ]]; then
    echo ""
    echo "Por favor, elige una opción:"
    echo "1. OpenAI API"
    echo "2. AssemblyAI"
    echo "3. Azure Speech"
    echo "4. AWS Transcribe"
    echo "5. Google Cloud"
    echo ""
    read -p "Opción (1-5): " -n 1 -r
    echo
    case $REPLY in
        1)
            echo "🚀 CONFIGURACIÓN DE OPENAI API:"
            echo "1. Ve a https://platform.openai.com/api-keys"
            echo "2. Inicia sesión o crea una cuenta"
            echo "3. Haz clic en 'Create new secret key'"
            echo "4. Copia la API key"
            echo "5. Crea un archivo .env en backend/ con:"
            echo "   OPENAI_API_KEY=tu_api_key_aqui"
            echo "6. Reinicia el servidor Rails"
            ;;
        2)
            echo "🆓 CONFIGURACIÓN DE ASSEMBLYAI:"
            echo "1. Ve a https://www.assemblyai.com/"
            echo "2. Crea una cuenta gratuita"
            echo "3. Ve a tu dashboard"
            echo "4. Copia tu API key"
            echo "5. Crea un archivo .env en backend/ con:"
            echo "   ASSEMBLY_AI_KEY=tu_api_key_aqui"
            echo "6. Reinicia el servidor Rails"
            ;;
        *)
            echo "Para las otras opciones, consulta la documentación en:"
            echo "backend/TRANSCRIPTION_SETUP.md"
            ;;
    esac
fi

echo ""
echo "✅ Configuración completada. ¡El sistema estará listo para transcribir!"
